CREATE TABLE IF NOT EXISTS User
(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Post
(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    userId int NOT NULL,
    datetime DATETIME NOT NULL
);


ALTER TABLE Post ADD CONSTRAINT FOREIGN KEY (userId) REFERENCES User(id);
